### ISSUE TITLE
Name glitched

### ISSUE THREAD

**Issue by Prajiad** [CreArts-Community/CreArts-Discord#13]
![image](https://user-images.githubusercontent.com/42892431/125332481-6154d780-e349-11eb-93d8-e2162959b670.png)

On Better Discord names are little bit broken, i've no idea if the same issue is on PowerCord too because i don't use it.
I've change only the Skins putting the Spotify version, nothing else.

**Comment by CorellanStoma** [comment]
Hmm do you use some plugins that could break it?

everything is fine if I switch to the spotify version in Better Discord:
![image](https://user-images.githubusercontent.com/58918358/125412526-4d4bbd00-e3bf-11eb-8fa8-38d01488ede1.png)

**Comment by Prajiad** [comment]
I was using "BetterFormattingRedux" i disabled it and tried another time but nothing changed :/
