### ISSUE TITLE
How to select theme skins

### ISSUE THREAD

**Issue by OmriOn** [CreArts-Community/CreArts-Discord#16]
How to select theme skins

THE DOCUMENTATION DOSENT EXIST FIX THE LINK

**Comment by Loremly** [comment]
U fix it lolz

**Comment by Vectorvr10** [comment]
You should change a few lines in the theme file, I just found out.
You have to enter the theme folder and change a few lines of the "theme.css" and "theme.scss" files.
In "theme.css" to deactivate the theme you have to add "/ *" to the active theme line, in "theme.scss" you have to add "//" to the active theme.
To activate a theme you have to delete the "/ *" and "//" mentioned above.
I attach a video where I do that.

https://user-images.githubusercontent.com/86861836/127417240-29c8fcf9-e740-4957-b4b8-449435e52cec.mp4

PD: "guardar" means "save" (I speak spanish)

**Comment by CorellanStoma** [comment]
Outdated from CreArts v2.
