### ISSUE TITLE
Question : How do I change between themes? 

### ISSUE THREAD

**Issue by SubNuclear** [CreArts-Community/CreArts-Discord#18]
I wanted to change to the black-green theme but i dont understand how to

**Comment by CorellanStoma** [comment]
Hi, currently you can change skins by editing the main files.

This will change in the next update,

for powercord you have to edit the theme.scss and for better discord you have to edit the crearts.theme.css file.
Skins are loaded by commenting or not.

Lines with // are not loaded
Lines without // are loaded.

The file should look like this:
![image](https://user-images.githubusercontent.com/58918358/130334153-043082bf-73d8-4dfd-8ffc-b0e995397532.png)

**Comment by Ventispurr** [comment]
im new to powercord.. do i have to  make a pull request for this?

**Comment by CorellanStoma** [comment]
> im new to powercord.. do i have to make a pull request for this?

to switch a skin, you actually need to edit the theme.scss in the themes folder. (Powercord)

This will change with v3, in v3 you only paste the skin code in the QuickCS/Custom CSS

I'm actually work on v3 but I cant say when it's done.

**Comment by Ventispurr** [comment]
thanks! i figured it out!! kinda like betterdiscord!

**Comment by CorellanStoma** [comment]
Outdated from CreArts v2.
