### ISSUE TITLE
High CPU load

### ISSUE THREAD

**Issue by LeonHenning** [CreArts-Community/CreArts-Discord#19]
The CPU load goes from about 2% to about 20% when I activate the Theme. Please try to optimize the CPU load

**Comment by vveeps** [comment]
Not sure if it's related (or even caused by the theme) but ever since I installed it, my client has started to freeze randomly requiring me to kill it from task manager and restart it. I love this theme a lot but the frequent freezing has started to get to me.

**Comment by CorellanStoma** [comment]
Thank you for the feedback, the current version is still loaded directly as SCSS and compiled by Powercord, with the next update skins will be loaded via the Quick CSS. Powercord and the other clients will then get a precompiled version in v2.4.0, I could imagine that this could fix the problem.  I think it's just too much code and overloads the client to compile it.

I have noticed that CSS had a difference in performance. The compiled CSS version runs fine in the browser, so I think it could be better with v2.4.0.

**Comment by LeinadUchiha** [comment]
I just tried version 2.3.0 and consumes me 50% of the graphic card having the discord in the background and I have a 4GB Rx570 and also consumes up to 800MB of RAM

**Comment by CorellanStoma** [comment]
Outdated Bug from CreArts v2.
