### ISSUE TITLE
[Bug Report] No settings icons

### ISSUE THREAD

**Issue by Willy-JL** [CreArts-Community/CreArts-Discord#20]
**Describe the bug**
I wanted to add settings icons for myself and tried adding the usual
```css
@import url(https://mwittrien.github.io/BetterDiscordAddons/Themes/_res/SettingsIcons.css);
```
but that didn't work, then I looked into the code for this theme itself and saw some very similar lines as if this theme was supposed to have settings icons natively, but I just can't get them to show.

**Screenshots**
![image](https://user-images.githubusercontent.com/49810075/134069286-bf41e2fb-5550-4c6b-9447-6c4639a7b308.png)
(I changed the accent colors myself with custom css, but at the root I'm using the Twitch skin)

**Operating System:**
Which operating system do you use?

- Linux

**Comment by CorellanStoma** [comment]
> **Describe the bug**
> I wanted to add settings icons for myself and tried adding the usual
> 
> ```css
> @import url(https://mwittrien.github.io/BetterDiscordAddons/Themes/_res/SettingsIcons.css);
> ```
> 
> but that didn't work, then I looked into the code for this theme itself and saw some very similar lines as if this theme was supposed to have settings icons natively, but I just can't get them to show.
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/49810075/134069286-bf41e2fb-5550-4c6b-9447-6c4639a7b308.png)
> (I changed the accent colors myself with custom css, but at the root I'm using the Twitch skin)
> 
> **Operating System:**
> Which operating system do you use?
> 
> * Linux

Hi, unfortunately, there were problems with the better discord version in the past. I will probably include it again in future updates, but at the moment I can't tell much about it.
