### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by zlyfer** [CreArts-Community/CreArts-Discord#21]
**Describe the bug**
"No thanks" button padding on invite modal is a bit weird.

**To Reproduce**

1. Open an invite link from a server you didn't join yet.
2. Let it redirect to Discord.
3. See the weird "No thanks" button in the invite modal.

**Expected behaviour**
Button should be same padding like the "Join" button.

**Screenshots**
![image](https://user-images.githubusercontent.com/7332940/134435761-158384e2-2047-4086-8f5e-ceaffecb5bb9.png)
![image](https://user-images.githubusercontent.com/7332940/134435767-98f17cca-93b0-448e-b7bf-b96d418aade7.png)

**Operating System:**
Which operating system do you use?

- [ ] Linux
- [x] Windows
- [ ] macOS

**Additional context**
-

**Comment by CorellanStoma** [comment]
Outdated Bug from CreArts v2.
