### ISSUE TITLE
[Bug Report] DM popups not working properly

### ISSUE THREAD

**Issue by SleepyZzed** [CreArts-Community/CreArts-Discord#22]
**Describe the bug**
Whenever dmd by multiple users only one avatar appears and it will always appear at the very bottom, very hard to notice when dmd due to this.

Image also seems to pop up in the default area but then snaps to the bottom

**To Reproduce**
Steps to reproduce the behaviour:

1. Get messaged by another user'...'

**Expected behaviour**
Dm be above server region

**Screenshots**

**Operating System:**
Which operating system do you use?

- Linux
- Windows
- macOS

**Additional context**

**Comment by CorellanStoma** [comment]
Outdated Bug from CreArts v2.
