### ISSUE TITLE
Side bar is glitched

### ISSUE THREAD

**Issue by Yalfabeth** [CreArts-Community/CreArts-Discord#23]
![image](https://user-images.githubusercontent.com/88809729/141646720-031fe02b-69b1-4383-b6c7-a3ece36e61f9.png)
my sidebar looks like this, any suggestions how to fix it?

**Comment by ItsTatsuya** [comment]
There are two ways to solve this issue
1. Either wait for v3.0.0 
2. Go to be pastebin link below and copy and paste it to  notepad and save it as x.theme.css and install this theme like usual
https://pastebin.com/v38KQJkV
