### ISSUE TITLE
[Bug Report] Channel names don't respect original capitalization

### ISSUE THREAD

**Issue by percheperche** [CreArts-Community/CreArts-Discord#40]
**Describe the bug**
If a channel is named "idea-sharing", it will be changed to "Idea Sharing". All "-"s are removed and every word's first letter is capitalized.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to "..."
2. Click on "...."
3. Scroll down to "...."

**Expected behaviour**

**Screenshots**

**Operating System:**
Which operating system do you use?

- [ ] Linux
- [x] Windows
- [ ] macOS

**Additional context**

**Comment by CorellanStoma** [comment]
Hi, this is not a bug but a feature, you can change this in the crearts.theme.css file:

https://github.com/CreArts-Community/CreArts-Discord/blob/ac10bdf43333c89bbb0ce3b6802a3128c58cdf35/clients/crearts.theme.css#L266

if you comment out the import line under /* ✅ Replace Dash */ this effect should disappear.

**Comment by percheperche** [comment]
Thank you
